config/routes.rb
Project::Application.routes.draw do

  get 'facade/index'
  get 'users/register'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  root 'facade#index'

  resources :users do
    get 'register', on: :collection
  end
  resources :timetables do
    get 'common_table', on: :collection
  end

end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
  validates :lid, uniqueness: true

  
  def color
    '#' + id.hash.abs.to_s(16)[0,6]
  end
end

app/models/sugang.rb
class Sugang < ActiveRecord::Base
	belongs_to :user
	belongs_to :lecture

  validates :user_id, uniqueness: {scope: :lecture_id}
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
  # it has name
  belongs_to :user
  has_many :items, class_name: TimetableItem

  validates :name, uniqueness: {scope: :user_id}, presence: true

  def users
    User.find_all_by_id(items.select(:user_id).distinct.map(&:user_id))
  end
end

app/models/timetable_item.rb
class TimetableItem < ActiveRecord::Base
  belongs_to :user
  belongs_to :lecture
  belongs_to :timetable

  # validates :user_id, uniqueness: {scope: :lecture_id}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :sugangs
  has_many :taking_lectures, {through: :sugangs, source: :lecture}, -> { where(status: 'taking') }
  has_many :timetables

  validates :sid, uniqueness: true
  after_save :crawl_lectures, if: :sid_changed?

  #User.first.taking_lectures << Lecture.first
  # then taking kkul
  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
	    user.provider = auth.provider
	    user.uid = auth.uid
	    user.name = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
	  end
	end

  def color
    '#' + id.hash.abs.to_s(16)[0,6]
  end

  def crawl_lectures
    taking_lectures.clear
    #for this semester
    payload = <<PAYLOAD
<?xml version="1.0" encoding=http://haksa.ajou.ac.kr/uni/uni/cour/tlsn/findCourPersonalTakingLessonAply.action"utf-8"?>
<root>
<params>
<param id="strYy" type="STRING">2014</param>
<param id="strShtmCd" type="STRING">U0002001</param>
<param id="strStdNo" type="STRING">#{sid}</param>
<param id="admin" type="STRING">admin</param>
<param id="AUuser.taking_lectures.create lid: array_id[i], name: array_name[i], time: array_time[i], credit: array_credit[i]     DIT9_ID" type="STRING"></param>
</params>
</root>
PAYLOAD
    # Rails.logger.info payload

    res = RestClient.post "http://haksa.ajou.ac.kr/uni/uni/cour/tlsn/findCourPersonalTakingLessonAply.action", payload, 
      :content_type => 'text/xml/SosFlexMobile;charset=utf-8'
      # :cookies => {PHAROS_VISITOR:'0000000001438fc7dae21310ca1e000f',Lib1Proxy2Ssn:'84686512' ,SSOGlobalLogouturl:'get^http://portal.ajou.ac.kr/com/sso/logout.jsp$', ssotoken:'tEk5WjTshDwsdHpdG1eCmjC4p9q%2Bh8TULRvM3zihMZhYhEwT9YYlG5lwMsgzRzlixqBp%2B06JR4MqyPxrx0c%2FEUbFjgiES3Ss90wIxdN6QYQLKnVO956ZfBu9gW5OAZDj3qgVTGZgBUXcpN0Q6MwBFw%3D%3D', JSESSIONID:'vKeZyEucqSOpwfpnHg47AXfXR6xpYhJbYh63amQgjBgIGAbDSR2Joe6YgynmJ88K.hakdang_servlet_engine1'}


    doc= Nokogiri::XML(res)
    doc.remove_namespaces!
    lecture_name = doc.css('sbjtKorNm').children
    lecture_time = doc.css('ltTmNm').children
    lecture_id = doc.css('tlsnNo').children
    lecture_credit = doc.css('tm').children

    array_name = Array.new
    array_time = Array.new
    array_id = Array.new
    array_credit = Array.new

    for data in lecture_name
      array_name <<data.to_s
    end
    for data2 in lecture_time
      array_time <<data2.to_s
    end
    for data3 in lecture_id
      array_id <<data3.to_s
    end
    for data4 in lecture_credit
      array_credit <<data4.to_s
    end
    # Rails.logger.info array_name.length
    
    if array_name.length != 0
      for i in 0...array_name.length
        unless taking_lectures.where(lid: array_id[i]).exists?
          unless lecture = Lecture.find_by_lid(array_id[i])
            lecture = Lecture.create lid: array_id[i], name: array_name[i], time: array_time[i], credit: array_credit[i]
          end
          taking_lectures << lecture
        end
       end
    end

    # Rails.logger.info array_name
    # Rails.logger.info array_time
    # Rails.logger.info array_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user
end

app/controllers/facade_controller.rb
class FacadeController < ApplicationController
  def index
    redirect_to user_path(current_user) if current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    # sign_in user
    session[:user_id] = user.id
    redirect_to root_url
    # redirect_to '/timetable/show'
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/timetables_controller.rb
class TimetablesController < ApplicationController
	def common_table
		@timetable = Timetable.new
	end

	def new
		@timetable = Timetable.new
	end

	def show
		@timetable = Timetable.find(params[:id])
	end

	def create

		@timetable = current_user.timetables.new
		if params[:sid]
			no_sids = params['sid'] - User.where("sid IN (?)", params['sid']).select(:sid).map(&:sid)
			no_sids.each do |sid|
				user = User.create(sid: sid)
			end

			User.where("sid IN (?)", params['sid']).each do |user|
				user.taking_lectures.where("time IS NOT NULL").each do |lecture|
					@timetable.items.new user: user, lecture: lecture
				end
			end
			@timetable.name = User.where("sid IN (?)", params['sid']).map{|user| user.name or user.sid }.join(" ")

		elsif params[:lectures]
			lids = params[:lectures]
			lids.each do |lid|
				@timetable.items.new(lecture: Lecture.find_by_lid(lid), user: current_user)
			end
			@timetable.name = "My timetable"
		end

		@timetable.save!

		redirect_to @timetable

	end

	def common_table2
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_users_informations_are_lack, except: [:register, :update]
  
  def check_users_informations_are_lack
    if current_user.nil?
      redirect_to :facade_index
      return
    end
    if current_user.sid.blank?
      redirect_to :users_register
      return
    end
  end


	def update
		User.where(sid:params[:user][:sid]).map(&:destroy)
		current_user.sid=params[:user][:sid]
		current_user.save!
		redirect_to :root
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/common_table_helper.rb
module CommonTableHelper
end

app/helpers/facade_helper.rb
module FacadeHelper
end

app/helpers/timetable_helper.rb
# encoding: utf-8

module TimetableHelper
  def timeslices_from_lecture(lecture) 
    lecture.time.split(/\([^\)]*\)/).map(&:strip).map {|str| [str[0],str[1,str.length]] }
  rescue Exception => e
    raise lecture.inspect
  end

  def css_from_timeslice(timeslice)
    css = ""
    css += "left: " + case timeslice[0]
    when '월'
      "0%"
    when '화'
      "20%"
    when '수'
      "40%"
    when '목'
      "60%"
    when '금'
      "80%"
    end + ";"

    css += "width: 20%;"


    top, bottom2 = case timeslice[1]
    when /^\d\d:\d\d~\d\d:\d\d$/
      timeslice[1].split('~').map{|t| q = t.split(':'); (q[0].to_i-9)*100/9.0+q[1].to_i*100/9.0/60 }
    when /^[ABCDEF]$/
      [(timeslice[1].ord - "A".ord) * 100 / 6.0, (timeslice[1].ord - "A".ord + 1) * 100 / 6.0]
    when /^[1234567890]+$/
      [(timeslice[1].to_i - 1) * 100 / 9.0, timeslice[1].to_i * 100 / 9.0]
    else
      raise timeslice[1]
    end
    bottom = 100 - bottom2


    css += "top: #{top}%; bottom: #{bottom}%;"

    css
  end
end

app/views/facade/index.html.erb
<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <%= link_to "Common timetable", common_table_timetable_index_path %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>

app/views/facade/next.html.erb
hey

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/timetable/common_table.html.erb
<%

%>


<form action="common_table2">
	<div id="sids">
		<div>
			<input name="sid[]" type="text" />
		</div>
			
	</div>
	<div>
		<button id="add-sid">Add sid</button>
	</div>
	<div>
		<input type="submit" value="Make common table" />
	</div>
</form>

<script>
	$('#add-sid').click(function(e) {
		$('#sids').append($('<div><input name="sid[]" type="text" /></div>'));
		e.preventDefault();
	});
</script>

app/views/timetables/_timetable.html.erb
<div class="common-table">
  <div class="common-table-left-col" >
    <div class="time"></div>
    <div class="time">A</div>
    <div class="time">B</div>
    <div class="time">C</div>
    <div class="time">D</div>
    <div class="time">E</div>
    <div class="time">F</div>
  </div>
  <div class="common-table-right-col" >
    <div class="common-table-header">
      <div class="day">월</div>
      <div class="day">화</div>
      <div class="day">수</div>
      <div class="day">목</div>
      <div class="day">금</div>
    </div>
    <div class="common-table-content">
    </div>
  </div>

  <div class="common-table-legend">
    <%= legend %>
  </div>
</div>
<script>
<%
  if timetable
    timetable.items.each do |item|
      timeslices_from_lecture(item.lecture).each do |timeslice|
%>
add_timeslice("<%=css_from_timeslice(timeslice)%>", "<%=if timetable.users.count > 1 then item.user.color else item.lecture.color end %>", "<%=item.lecture.lid%>"); //<%=item.lecture.time%>"
<%
      end
    end
  end
%>
</script>

app/views/timetables/common_table.html.erb
<%= form_for @timetable do %>
	<div id="sids">
		<div>
			<input name="sid[]" type="text" />
		</div>
			
	</div>
	<div>
		<button type="button" id="add-sid">Add sid</button>
	</div>
	<div>
		<input type="submit" value="Make common table" />
	</div>

<% end %>

<script>
	$('#add-sid').click(function(e) {
		$('#sids').append($('<div><input name="sid[]" type="text" /></div>'));
		$('#sids div:last-child input').focus()
	});
</script>

app/views/timetables/new.html.erb
<%= render partial: "timetable", locals: {timetable: @timetable, legend: capture do %>

<%= form_for @timetable do |f| %>
  
  <div style="overflow:hidden;">
    <div style="float: right;">
      <input type="submit" value="Submit" />
    </div>
  </div>

<% Lecture.all.each do |lecture| %>
    <div class="legend-item lecture" data-time="<%=lecture.time%>" data-lid="<%=lecture.lid%>" data-color="<%=lecture.color%>">
      <input type="checkbox" id="lecture_<%=lecture.lid%>" name="lectures[]" value="<%=lecture.lid%>" style="display: none; "/>
      <div class="legend-item-color" style="background-color: <%=lecture.color%>; visibility: hidden;"></div>
      <div class="legend-item-text">
        <label for="lecture_<%=lecture.lid%>" style="display: block;"> <%= lecture.name %> </label>
      </div>
    </div>
<% end %>
<% end %>
<% end } %>

app/views/timetables/show.html.erb
<%= render partial: "timetable", locals: {timetable: @timetable, legend: capture do %>

  <% if @timetable.users.count > 1 %>
      <% @timetable.users.each do |user| %>

      <div class="legend-item">
        <div class="legend-item-color" style="background-color: <%=user.color%>;"></div>
        <div class="legend-item-text"><%= if user.name then user.name else user.sid end%></div>
      </div>

    <% end %>

  <% else %>

  <% @timetable.items.includes(:lecture).map(&:lecture).each do |lecture| %>
    <div class="legend-item lecture" data-time="<%=lecture.time%>" data-lid="<%=lecture.lid%>" data-color="<%=lecture.color%>">
      <input type="checkbox" id="lecture_<%=lecture.lid%>" name="lectures[]" value="<%=lecture.lid%>" style="display: none; "/>
      <div class="legend-item-color" style="background-color: <%=lecture.color%>;"></div>
      <div class="legend-item-text">
        <label for="lecture_<%=lecture.lid%>" style="display: block;"> <%= lecture.name %> </label>
      </div>
    </div>
  <% end %>


  <% end %>

<% end } %>

app/views/users/register.html.erb
<%= form_for current_user do |f|%>
	<%= f.label :sid %>
	<%= f.text_field :sid %>
	<!--<%= f.submit %>-->
<%end%>

app/views/users/show.html.erb
<strong><%= current_user.name %></strong>님 
<%= link_to "Sign out", signout_path, id: "sign_out" %>

<ul>
  <li><%=current_user.name%></li>
  <li>정보 컴퓨터 공학과(가짜)</li>
  <li><%=current_user.sid%></li>
  <li>4학년(가짜)</li>
  <li>신입학(가짜)</li>
  <li>재학(가짜)</li>
</ul>

시간표
<ul>
  <% current_user.timetables.each do |timetable| %>
  <li> <%= link_to timetable.name, timetable %> </li>
  <% end %>
</ul>

<p>
  <%= link_to "공통시간표 만들기", common_table_timetables_path %>
</p>
<p>
  <%= link_to "새 시간표", :new_timetable %>  
</p>